services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hiring_platform
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nest:
    build: .
    container_name: nest-app
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: hiring_platform
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./nestjs.log:/app/nestjs.log
    command: ["npm", "run", "start:dev"]

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./nestjs.log:/var/log/nestjs.log
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  redis_data:
  loki_data:
  grafana_data:
